service: talking-backend 

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1 
  
      
functions:
  speak:
    handler: handler.speak
    events:
      - http: 
          path: speak
          method: post
          cors: true