service: talking-backend 

provider:
  name: aws
  runtime: nodejs12.0
  region: us-east-1 
  role : arn:aws:iam::916015747809:role/polly-actual-role 
      
functions:
  speak:
    handler: handler.speak
    events:
      - http: 
          path: speak
          method: post
          cors: true